/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExecutiveSummaryRouteImport } from './routes/executive-summary'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as SupplierRiskRouteImport } from './routes/supplier-risk'
import { Route as SupplyPlanningRouteImport } from './routes/supply-planning'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveSummaryRoute = ExecutiveSummaryRouteImport.update({
  id: '/executive-summary',
  path: '/executive-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierRiskRoute = SupplierRiskRouteImport.update({
  id: '/supplier-risk',
  path: '/supplier-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyPlanningRoute = SupplyPlanningRouteImport.update({
  id: '/supply-planning',
  path: '/supply-planning',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/executive-summary': typeof ExecutiveSummaryRoute
  '/forecasting': typeof ForecastingRoute
  '/supplier-risk': typeof SupplierRiskRoute
  '/supply-planning': typeof SupplyPlanningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/executive-summary': typeof ExecutiveSummaryRoute
  '/forecasting': typeof ForecastingRoute
  '/supplier-risk': typeof SupplierRiskRoute
  '/supply-planning': typeof SupplyPlanningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/executive-summary': typeof ExecutiveSummaryRoute
  '/forecasting': typeof ForecastingRoute
  '/supplier-risk': typeof SupplierRiskRoute
  '/supply-planning': typeof SupplyPlanningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/executive-summary'
    | '/forecasting'
    | '/supplier-risk'
    | '/supply-planning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/executive-summary'
    | '/forecasting'
    | '/supplier-risk'
    | '/supply-planning'
  id:
    | '__root__'
    | '/'
    | '/executive-summary'
    | '/forecasting'
    | '/supplier-risk'
    | '/supply-planning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExecutiveSummaryRoute: typeof ExecutiveSummaryRoute
  ForecastingRoute: typeof ForecastingRoute
  SupplierRiskRoute: typeof SupplierRiskRoute
  SupplyPlanningRoute: typeof SupplyPlanningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-summary': {
      id: '/executive-summary'
      path: '/executive-summary'
      fullPath: '/executive-summary'
      preLoaderRoute: typeof ExecutiveSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-risk': {
      id: '/supplier-risk'
      path: '/supplier-risk'
      fullPath: '/supplier-risk'
      preLoaderRoute: typeof SupplierRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply-planning': {
      id: '/supply-planning'
      path: '/supply-planning'
      fullPath: '/supply-planning'
      preLoaderRoute: typeof SupplyPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExecutiveSummaryRoute: ExecutiveSummaryRoute,
  ForecastingRoute: ForecastingRoute,
  SupplierRiskRoute: SupplierRiskRoute,
  SupplyPlanningRoute: SupplyPlanningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
